=== BrondonJores/DUT-2/TP_xml/tp_serie2/Exercice2DTD.dtd
<!ELEMENT bibliographie ((livre+, article+) | avis)*>
<!ELEMENT livre (titre, auteurs, tomes, editeur, lieu-edition, lieu-impression)>
<!ATTLIST livre ISBN ID #REQUIRED>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT auteurs (auteur+)>
<!ELEMENT auteur (nom)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT tomes (tome+)>
<!ELEMENT tome (nombre-page)>
<!ELEMENT nombre-page (#PCDATA)>
<!ELEMENT lieu-edition (#PCDATA)>
<!ELEMENT editeur (#PCDATA)>
<!ELEMENT lieu-impression (#PCDATA)>
<!ELEMENT article (titre, auteurs, references)>
<!ELEMENT references (reference+)>
<!ELEMENT reference (nom, numero-page, annee, numero-journal)>
<!ELEMENT numero-page (page+)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT annee (#PCDATA)>
<!ELEMENT numero-journal (#PCDATA)>
<!ELEMENT avis (#PCDATA)>

=== BrondonJores/DUT-2/TP_xml/tp_serie2/Exercice2.xml
<?xml version='1.1' encoding="UTF-8" ?> 
<!DOCTYPE bibliographie SYSTEM "Exercice2DTD.dtd">

<bibliographie>
    <livre ISBN="LIV121">
        <titre>Livre 1</titre>
        <auteurs>
            <auteur> 
                <nom>Auteur1</nom> 
            </auteur>
            <auteur> 
                <nom>Auteur2</nom> 
            </auteur>
        </auteurs>
        <tomes>
            <tome> 
                <nombre-page>25</nombre-page> 
            </tome>
            <tome> 
                <nombre-page>30</nombre-page>
            </tome>
        </tomes>
        <editeur>Editeur1</editeur>
        <lieu-edition>Lieu1</lieu-edition>
        <lieu-impression>Lieu1I</lieu-impression>
    </livre>

    <article>
        <titre>Article1</titre>
        <auteurs>
            <auteur>
                <nom>Auteur3</nom>
            </auteur>
            <auteur>
                <nom>Auteur4</nom>
            </auteur>
        </auteurs>
        <references>
            <reference>
                <nom>Journal1</nom>
                <numero-page>
                    <page>2</page>
                    <page>3</page>
                    <page>5</page>
                </numero-page>
                <annee>2025</annee>
                <numero-journal>JRN213</numero-journal>
            </reference>
        </references>
    </article>

    <avis>
        Ceci est un avis optionnel
    </avis>
</bibliographie>
